name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: docker://ekohandel/chisel:latest
        with:
          entrypoint: sbt
          args: test
